// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static dynamic get currentPlatform {
    return null;
    /*
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
    */
  }

  /*
  static const FirebaseOptions android = FirebaseOptions(
        apiKey: "AIzaSyD54EYCJZbrMa3ohzowFULJf1fGwojqKRw",
    authDomain: "irpay-6f8e0.firebaseapp.com",
    projectId: "irpay-6f8e0",
    storageBucket: "irpay-6f8e0.firebasestorage.app",
    messagingSenderId: "908759286544",
    appId: "1:908759286544:web:e20e499963d03f5b8bdb95",
    measurementId: "G-9E4C5S3MXZ"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-waGILDrl7BV0mPbadUUhyYHqF1qlxaM',
    appId: '1:364630175808:ios:4661274da087cdd9786fa5',
    messagingSenderId: '364630175808',
    projectId: 'ovopay-app',
    storageBucket: 'ovopay-app.firebasestorage.app',
    iosBundleId: 'com.ovosolution.ovopay',
  );
  */
}
